apiVersion: v1
kind: ConfigMap
metadata:
  name: php-code
data:
  index.php: |
    <?php
    echo "Hello Kubernetes PHP!";
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:8.3-fpm-alpine
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: php-code-volume
          mountPath: /var/www/html
      volumes:
      - name: php-code-volume
        configMap:
          name: php-code
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
  - port: 9000
    targetPort: 9000